# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='date_created',
            new_name='created_on',
        ),
    ]
