# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20170814_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='created_on',
            new_name='date_created',
        ),
    ]
