# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20170814_1324'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Work',
            new_name='Post',
        ),
    ]
