# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20170816_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brief', models.CharField(max_length=300)),
                ('entry_period', models.DateTimeField(blank=True, null=True)),
                ('vote_period', models.DateTimeField(blank=True, null=True)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='comp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Competition'),
        ),
    ]
