# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20170822_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
    ]
