# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20170825_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='entry_period',
            new_name='entry_period_end',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='vote_period',
            new_name='entry_period_start',
        ),
        migrations.AddField(
            model_name='competition',
            name='vote_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='vote_period_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
    ]
