# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20170826_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
