# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_competition_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Competition'),
        ),
    ]
