# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20170826_0730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='entry_period_end',
            new_name='entry_period_fin',
        ),
    ]
