# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20170826_0802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comp_id',
            new_name='comp',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='winner',
        ),
        migrations.AddField(
            model_name='competition',
            name='entries',
            field=models.ManyToManyField(to='post.Post'),
        ),
    ]
