# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 07:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_remove_competition_entries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='is_active',
        ),
    ]
