# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_remove_competition_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='can_vote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
