# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0023_auto_20170829_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='can_vote',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='is_active',
        ),
    ]
