# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 02:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0024_auto_20170829_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='post.Competition')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='post.Post')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
