# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0025_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='vote_count',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Vote'),
        ),
    ]
