# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0026_auto_20170830_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='vote_count',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Vote'),
        ),
    ]
