# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0027_auto_20170830_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='vote_count',
        ),
    ]
