# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 04:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0028_remove_post_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='winner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Competition'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
