# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0030_competition_prize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[(None, b''), (b'Poem', b'Poem'), (b'Short', b'Short Story'), (b'Essay', b'Essay'), (b'Memoir', b'Memoir'), (b'Letter', b'Letter'), (b'Script', b'script'), (b'Speech', b'Speech')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(blank=True, choices=[(b'Nonfiction', ((None, b''), (b'Expose', b'Expository'), (b'Argument', b'Argumentative'), (b'Opinion', b'Opinion'))), (b'Fiction', ((None, b''), (b'Comedy', b'Comedy'), (b'Drama', b'Drama'), (b'Horror', b'Horror'), (b'Romance', b'Romance'), (b'Tragedy', b'Tragedy'), (b'Tragic Comedy', b'Tragicomedy'), (b'Fantasy', b'Fantasy'), (b'Myth', b'Mythology')))], max_length=20, null=True),
        ),
    ]
