# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0031_auto_20170910_0625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='comp',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voter',
        ),
        migrations.AlterField(
            model_name='post',
            name='comp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competition', to='post.Competition'),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
