# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0032_auto_20170914_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='winner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='post.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='post.Competition'),
        ),
    ]
