# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 02:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0034_auto_20170916_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='winner',
        ),
        migrations.AddField(
            model_name='competition',
            name='winner',
            field=models.ManyToManyField(blank=True, null=True, related_name='winner', to='post.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
