# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0035_auto_20170917_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='competition',
            name='winner',
        ),
        migrations.AddField(
            model_name='competition',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
