# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0036_auto_20170917_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='post.Competition'),
        ),
    ]
