# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0037_auto_20170920_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
