# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0038_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'images', validators=[post.models.validate_image]),
        ),
    ]
