# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 08:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='post.Competition'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='post.Post'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
