# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 07:16
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars', validators=[accounts.models.validate_image]),
        ),
    ]
