# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20171012_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stripe_id',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
