# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 10:45
from __future__ import unicode_literals

import accounts.models
from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20171003_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=smartfields.fields.ImageField(blank=True, null=True, upload_to='avatars', validators=[accounts.models.validate_image]),
        ),
    ]
