# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 06:12
from __future__ import unicode_literals

import accounts.models
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20171008_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[accounts.models.validate_image], verbose_name='avatars'),
        ),
    ]
